/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.crisprueba.juegoblackjack;
import java.util.ArrayList;
import java.util.Random;
/**
 *
 * @author crist
 */




class Carta {
    private String palo;
    private String valor;
    private int valorNumerico;

    public Carta(String palo, String valor, int valorNumerico) {
        this.palo = palo;
        this.valor = valor;
        this.valorNumerico = valorNumerico;
    }

    public String getPalo() {
        return palo;
    }

    public String getValor() {
        return valor;
    }

    public int getValorNumerico() {
        return valorNumerico;
    }

    public void setValorNumerico(int valorNumerico) {
        this.valorNumerico = valorNumerico;
    }

    @Override
    public String toString() {
        return valor + " de " + palo;
    }
}

class Baraja {
    private ArrayList<Carta> cartas = new ArrayList<>();
    private Random random = new Random();

    public Baraja() {
        String[] palos = {"Corazones", "Tréboles", "Picas", "Diamantes"};
        String[] valores = {"2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K", "A"};
        int[] valoresNumericos = {2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 10, 10, 11};

        // Generar todas las cartas
        for (String palo : palos) {
            for (int i = 0; i < valores.length; i++) {
                cartas.add(new Carta(palo, valores[i], valoresNumericos[i]));
            }
        }
    }

    public Carta darCartaAleatoria() {
        int indice = random.nextInt(cartas.size());
        return cartas.get(indice);
    }
}




public class PantallaJuego extends javax.swing.JFrame {

    
    
     private Baraja baraja;
    private ArrayList<Carta> manoUsuario;
    private ArrayList<Carta> manoCasa;
    
    /**
     * Creates new form PantallaJuego
     */
    public PantallaJuego() {
        initComponents();
        nuevoJuego();
       
      
    }

    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Pedir Carta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Nuevo Juego");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Completo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(jButton2)
                .addContainerGap(335, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void ocultar(){
    jButton1.setVisible(true);
    jButton3.setVisible(true);
    }
    
    
    
    
      private void nuevoJuego() {
        baraja = new Baraja();
        manoUsuario = new ArrayList<>();
        manoCasa = new ArrayList<>();
        manoUsuario.add(baraja.darCartaAleatoria());
        manoUsuario.add(baraja.darCartaAleatoria());
        manoCasa.add(baraja.darCartaAleatoria());
        manoCasa.add(baraja.darCartaAleatoria());
        ocultar();
        actualizarPantalla();
    }

    
     private int calcularValor(ArrayList<Carta> mano) {
        int total = 0;
        int numAses = 0;

        for (Carta carta : mano) {
            total += carta.getValorNumerico();
            if (carta.getValor().equals("A")) {
                numAses++;
            }
        }

        // Ajustar el valor del As si es necesario
        while (total > 21 && numAses > 0) {
            total -= 10; // Si el total excede 21, contamos el As como 1 en lugar de 11
            numAses--;
        }

        return total;
    }

    private void actualizarPantalla() {
        int valorUsuario = calcularValor(manoUsuario);
        int valorCasa = calcularValor(manoCasa);

        System.out.println("Tu mano: " + manoUsuario + " (Valor: " + valorUsuario + ")");
        System.out.println("Mano de la casa: " + manoCasa.get(0) + " y otra carta oculta");
        System.out.println("");

        if (valorUsuario > 21) {
            System.out.println("Perdiste, tu puntuación es mayor a 21");
            System.out.println("");
            ocultar();
        }
    }

    private void mostrarResultado() {
        int valorUsuario = calcularValor(manoUsuario);
        int valorCasa = calcularValor(manoCasa);

        System.out.println("Tu mano: " + manoUsuario + " (Valor: " + valorUsuario + ")");
        System.out.println("Mano de la casa: " + manoCasa + " (Valor: " + valorCasa + ")");
        System.out.println("");
        while (valorCasa < 17) {
            manoCasa.add(baraja.darCartaAleatoria());
            valorCasa = calcularValor(manoCasa);
        }

        if (valorCasa > 21 || valorUsuario > valorCasa) {
            System.out.println("¡Ganaste! El crupier se pasó o tienes mejor puntuación.");
            System.out.println("");
            ocultar();
        } else if (valorCasa == valorUsuario) {
            System.out.println("Empate.");
            System.out.println("");
            ocultar();
        } else {
            System.out.println("Perdiste, el crupier tiene mejor puntuación.");
            System.out.println("");
            ocultar();
        }
    }

  
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    manoUsuario.add(baraja.darCartaAleatoria());
    actualizarPantalla();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      nuevoJuego();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        mostrarResultado();
        jButton3.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed


    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
